name: NDMA Auto Scraper

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:      # Allows you to click "Run" manually

jobs:
  scrape-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          cd ndma
          pip install -r requirements.txt

      - name: Run Scraper
        env:
          # This pulls the JSON from your GitHub Repository Secrets
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        working-directory: ./ndma
        run: python cron_scraper.py